services:
  vaultwarden:
    image: vaultwarden/server:1.34.3
    container_name: vaultwarden
    restart: always
    volumes:
      - ./.volumes/vw-data:/data
    ports:
      - 127.0.0.1:20080:80
    env_file:
      - .env
    networks:
      - internal

  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare-tunnel
    command: tunnel run
    env_file:
      - .env
    networks:
      - internal

networks:
  internal:
    external: true
    name: internal
